/**
 * The 36 moon signs (Player's Book p175), an optional rule at character
 * creation: 12 moons, each with a waxing, a full, and a waning phase.
 *
 * **GENERATED by extract-lore.mjs — do not edit by hand.** Every row was read
 * out of the PDF and held against a second rendering of the same page; the
 * effects are the book's own words, because a paraphrase of a rule is a
 * different rule.
 *
 * **Only characters born in the mortal world have one** — mortals and demi-fey,
 * which in this book means everybody except elves and grimalkins. The sheet
 * says so beside the picker rather than refusing the choice: a table may rule
 * otherwise, and the module has no business being the one to stop them.
 *
 * The d100 range is kept even though nothing rolls on it yet. It is what makes
 * the table the book's table rather than a list of 36 things, and rolling one
 * is the procedure the book actually prescribes.
 */
export interface MoonSign {
  /** The d100 range this sign is rolled on, as the book prints it. */
  range: string;
  /** The moon of the month: Grinning, Dead, Beast, … */
  moon: string;
  phase: "waxing" | "full" | "waning";
  /** What it does, in the book's words. */
  effect: string;
}

export const MOON_SIGNS: MoonSign[] = [
  { range: "01-03", moon: "Grinning", phase: "waxing",
    effect: "50% chance of guardian undead ignoring the character's presence. (Though they act normally if provoked.)" },
  { range: "04", moon: "Grinning", phase: "full",
    effect: "+1 bonus to Saving Throws against the powers of undead monsters." },
  { range: "05-07", moon: "Grinning", phase: "waning",
    effect: "+1 Attack bonus against undead monsters." },
  { range: "08-10", moon: "Dead", phase: "waxing",
    effect: "+1 bonus to Attack and Damage Rolls the Round after killing a foe." },
  { range: "11", moon: "Dead", phase: "full",
    effect: "If killed by non-magical means, the character returns to life after 1 Turn with 1 Hit Point. Their Constitution and Wisdom are permanently halved (to a minimum score of 3). This supernatural avoidance of death only takes effect once ever." },
  { range: "12-14", moon: "Dead", phase: "waning",
    effect: "Undead monsters attack all others in the party before attacking the character." },
  { range: "15-17", moon: "Beast", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with dogs and horses." },
  { range: "18", moon: "Beast", phase: "full",
    effect: "Wild animals attack all others in the party before attacking the character." },
  { range: "19-21", moon: "Beast", phase: "waning",
    effect: "+1 Attack bonus against wolves and bears." },
  { range: "22-24", moon: "Squamous", phase: "waxing",
    effect: "Effects of poison are delayed by 1 Turn." },
  { range: "25", moon: "Squamous", phase: "full",
    effect: "+2 bonus to Saving Throws against the breath attacks and magical powers of wyrms and dragons." },
  { range: "26-29", moon: "Squamous", phase: "waning",
    effect: "+1 Attack bonus against serpents and wyrms." },
  { range: "30-33", moon: "Knight's", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with nobles." },
  { range: "34", moon: "Knight's", phase: "full",
    effect: "+1 AC bonus against attacks with metal weapons." },
  { range: "35-38", moon: "Knight's", phase: "waning",
    effect: "On a tied Initiative roll when in melee with knights or soldiers, the character acts first, as if they had won." },
  { range: "39-42", moon: "Rotting", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with sentient fungi." },
  { range: "43", moon: "Rotting", phase: "full",
    effect: "+2 AC bonus against attacks by fungal monsters." },
  { range: "44-47", moon: "Rotting", phase: "waning",
    effect: "In the character's presence, fungal monsters suffer a -1 penalty to Attack and Damage Rolls." },
  { range: "48-51", moon: "Maiden's", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with demi-fey." },
  { range: "52", moon: "Maiden's", phase: "full",
    effect: "+2 bonus to Saving Throws against charms and glamours." },
  { range: "53-56", moon: "Maiden's", phase: "waning",
    effect: "+1 bonus to Attack and Damage Rolls against shape-changers and those cloaked with illusions." },
  { range: "57-60", moon: "Witch's", phase: "waxing",
    effect: "When the character receives magical healing, they gain 1 additional Hit Point. This applies at most once per day to each type of magical healing (e.g. specific spell, Class trait, potion, etc.)." },
  { range: "61", moon: "Witch's", phase: "full",
    effect: "+1 bonus to Saving Throws against holy magic." },
  { range: "62-65", moon: "Witch's", phase: "waning",
    effect: "+1 bonus to Attack Rolls against witches and holy spell casters." },
  { range: "66-69", moon: "Robber's", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with Chaotic mortals." },
  { range: "70", moon: "Robber's", phase: "full",
    effect: "+1 AC bonus against attacks by Chaotic mortals, fairies, or demi-fey." },
  { range: "71-74", moon: "Robber's", phase: "waning",
    effect: "+1 Attack bonus against Chaotic mortals, fairies, and demi-fey." },
  { range: "75-78", moon: "Goat", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with breggles (including crookhorns)." },
  { range: "79", moon: "Goat", phase: "full",
    effect: "Breggles (including crookhorns) attack all others in the party before attacking the character." },
  { range: "80-83", moon: "Goat", phase: "waning",
    effect: "+1 Attack bonus against breggles (including crookhorns)." },
  { range: "84-87", moon: "Narrow", phase: "waxing",
    effect: "+2 bonus to Charisma (maximum 18) when interacting with fairies, but suffer a -1 penalty to all Saving Throws against fairy magic." },
  { range: "88", moon: "Narrow", phase: "full",
    effect: "If the character is afflicted by a curse or a Geas spell, there is a 1-in-4 chance of the caster also being affected by their own magic." },
  { range: "89-92", moon: "Narrow", phase: "waning",
    effect: "+1 Attack bonus against fairies and demi-fey." },
  { range: "93-96", moon: "Black", phase: "waxing",
    effect: "+1 bonus to Search Checks to find secret doors." },
  { range: "97", moon: "Black", phase: "full",
    effect: "+2 bonus to AC and Saving Throws when surprised." },
  { range: "98-00", moon: "Black", phase: "waning",
    effect: "+2 bonus to Saving Throws versus illusions and glamours." },
];

/** "Grinning moon, waxing" — how a sign is named on the sheet and in a block. */
export function moonSignLabel(sign: MoonSign): string {
  return `${sign.moon} moon, ${sign.phase}`;
}

/** The whole thing on one line, which is what the sheet's own field holds. */
export function moonSignLine(sign: MoonSign): string {
  return `${moonSignLabel(sign)} — ${sign.effect}`;
}

/** The moons in the order of the year, each with its three phases. */
export function moonSignsByMoon(): { moon: string; signs: MoonSign[] }[] {
  const order: string[] = [];
  const byMoon = new Map<string, MoonSign[]>();
  for (const sign of MOON_SIGNS) {
    if (!byMoon.has(sign.moon)) {
      byMoon.set(sign.moon, []);
      order.push(sign.moon);
    }
    byMoon.get(sign.moon)!.push(sign);
  }
  return order.map((moon) => ({ moon, signs: byMoon.get(moon)! }));
}
